//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/input_control/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""MovementZone"",
            ""id"": ""b587f8ae-80d1-4487-b90f-99d6968a2c7e"",
            ""actions"": [
                {
                    ""name"": ""placePoint"",
                    ""type"": ""Button"",
                    ""id"": ""1242725f-34e3-49ed-869f-aed9fa9088ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""cancel"",
                    ""type"": ""Button"",
                    ""id"": ""4c40d480-7ef7-4b1a-a5ea-af888e19094d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""1ad44262-b94e-48b1-aa6d-538fd1ce467b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46a1de04-9694-475f-9c73-7c47d73d4dbe"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap,Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""placePoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e055893-2dd5-478e-94d6-91721afba45c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8824b5f2-4096-4c59-88ec-ca13f75d5f18"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MovementZone
        m_MovementZone = asset.FindActionMap("MovementZone", throwIfNotFound: true);
        m_MovementZone_placePoint = m_MovementZone.FindAction("placePoint", throwIfNotFound: true);
        m_MovementZone_cancel = m_MovementZone.FindAction("cancel", throwIfNotFound: true);
        m_MovementZone_mousePosition = m_MovementZone.FindAction("mousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MovementZone
    private readonly InputActionMap m_MovementZone;
    private List<IMovementZoneActions> m_MovementZoneActionsCallbackInterfaces = new List<IMovementZoneActions>();
    private readonly InputAction m_MovementZone_placePoint;
    private readonly InputAction m_MovementZone_cancel;
    private readonly InputAction m_MovementZone_mousePosition;
    public struct MovementZoneActions
    {
        private @InputController m_Wrapper;
        public MovementZoneActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @placePoint => m_Wrapper.m_MovementZone_placePoint;
        public InputAction @cancel => m_Wrapper.m_MovementZone_cancel;
        public InputAction @mousePosition => m_Wrapper.m_MovementZone_mousePosition;
        public InputActionMap Get() { return m_Wrapper.m_MovementZone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementZoneActions set) { return set.Get(); }
        public void AddCallbacks(IMovementZoneActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementZoneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementZoneActionsCallbackInterfaces.Add(instance);
            @placePoint.started += instance.OnPlacePoint;
            @placePoint.performed += instance.OnPlacePoint;
            @placePoint.canceled += instance.OnPlacePoint;
            @cancel.started += instance.OnCancel;
            @cancel.performed += instance.OnCancel;
            @cancel.canceled += instance.OnCancel;
            @mousePosition.started += instance.OnMousePosition;
            @mousePosition.performed += instance.OnMousePosition;
            @mousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IMovementZoneActions instance)
        {
            @placePoint.started -= instance.OnPlacePoint;
            @placePoint.performed -= instance.OnPlacePoint;
            @placePoint.canceled -= instance.OnPlacePoint;
            @cancel.started -= instance.OnCancel;
            @cancel.performed -= instance.OnCancel;
            @cancel.canceled -= instance.OnCancel;
            @mousePosition.started -= instance.OnMousePosition;
            @mousePosition.performed -= instance.OnMousePosition;
            @mousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IMovementZoneActions instance)
        {
            if (m_Wrapper.m_MovementZoneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovementZoneActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementZoneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementZoneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovementZoneActions @MovementZone => new MovementZoneActions(this);
    public interface IMovementZoneActions
    {
        void OnPlacePoint(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
